#!/usr/bin/env python3
"""Refresh the repository-native Unity Unified Harness routers.

This script owns only the three canonical routers and two compatibility aliases. It does
not install tools, launch Unity, edit package manifests, or depend on the Hub.
"""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANAGED_MARKER = "<!-- Generated by scripts/refresh_harness_routing.py -->"


def root_router() -> str:
    return f"""{MANAGED_MARKER}
# DevAccelerationSystem Satellite Router

## Purpose

This is the canonical Codex router for the standalone `DevAccelerationSystem`
repository and for the same repository when mounted in `AIFoxsterDevHub`.
The local contract is complete without the Hub.

## Required Load Order

1. Read this file from the first line through EOF.
2. Read `Docs/ai/unity-unified-harness-adapter.md` from the first line through EOF.
3. Select exactly one target project and read its nearest `AGENTS.md` through EOF.
4. Read that project's relevant `Assets/AIOutput/ProjectMemory/` owners.
5. Load historical `Assets/AIOutput/` reports only when dated evidence is relevant.
6. If the repository is mounted in the Hub and `../AGENTS.md` plus
   `../AIRoot/Modules/XUUnity/` exist, optionally augment this local contract with
   the Hub router and only the task-relevant XUUnity protocol files.

Missing Hub files are normal standalone state, not an error. `AIModules`
symlinks are legacy host conveniences and are never required for standalone use.

## Workspace Boundaries

- Canonical package and editor-tooling source: `DevAccelerationSystem/`.
- Tracked consumer proof project: `DevAccelerationSystem.DemoProject/`.
- Optional ignored local repro project: `DAS.LocalProject/`, when present.
- Shared package changes start in the canonical source and use a consumer only
  for focused integration proof.
- `DAS.LocalProject/` is supplementary evidence and never tracked release proof.

## Native Execution Contract

- Use the native Codex runtime and existing Unity/XUUnity tooling.
- Do not add an agent runtime, orchestrator, workflow engine, task database,
  provider abstraction, daemon, queue, or extra process hierarchy.
- Keep the path compact: local kernel -> satellite adapter -> optional XUUnity
  guidance -> focused proof -> zero or one compact outcome record.
- Never widen a docs-only or routing-only change into Unity product regression.

## Git Boundary

This directory is its own Git repository when mounted in the Hub. Review and
commit it independently before any parent gitlink update.
"""


def project_router(*, project_name: str, project_kind: str, role: str) -> str:
    return f"""{MANAGED_MARKER}
# Project Router: {project_name}

## Purpose

Canonical Codex entrypoint for `{project_name}`.

## Load Order

1. Read `../AGENTS.md` and `../Docs/ai/unity-unified-harness-adapter.md` through EOF.
2. Read this file through EOF.
3. Read relevant owners under `Assets/AIOutput/ProjectMemory/`.
4. Load task-specific XUUnity files only when Hub augmentation is available and useful.

The repository-local router and adapter are sufficient in a standalone clone.
Do not require `../../AIRoot`, `../../AIModules`, or a parent Hub checkout.

## Project Context

- Project: `{project_name}`
- Project kind: `{project_kind}`
- Role: {role}
- Exact tracked editor: Unity `2022.3.62f3` revision `96770f904ca7`
- Priority: Stability > Performance > Maintainability

## Routing

- Apply the adapter's `docs`, `ordinary`, `high-risk`, or `release` lane.
- Keep package-source proof distinct from consumer-project proof.
- Record exact Unity version, build target, test mode, and proof ceiling.
- Do not import iOS accessibility or Apple-surface rules unless the changed
  Unity feature actually owns such a requirement.
- Do not edit MCP pins/configuration or package/product runtime merely to create proof.
"""


FILES = {
    ROOT / "AGENTS.md": root_router(),
    ROOT / "DevAccelerationSystem" / "AGENTS.md": project_router(
        project_name="DevAccelerationSystem",
        project_kind="unity_package_and_editor_tooling_source",
        role="canonical source for three package roots and editor tooling",
    ),
    ROOT / "DevAccelerationSystem.DemoProject" / "AGENTS.md": project_router(
        project_name="DevAccelerationSystem.DemoProject",
        project_kind="unity_package_validation_demo",
        role="tracked local-file UPM consumer and integration-proof surface",
    ),
}

ALIASES = {
    ROOT / "DevAccelerationSystem" / "Agents.repo.md": "../AGENTS.md",
    ROOT / "DevAccelerationSystem.DemoProject" / "Agents.repo.md": "../AGENTS.md",
}


def normalized(text: str) -> str:
    return text.rstrip() + "\n"


def alias_target(path: Path) -> str | None:
    if path.is_symlink():
        return path.readlink().as_posix()
    if path.is_file():
        return path.read_text(encoding="utf-8").strip()
    return None


def check() -> int:
    stale = []
    for path, expected in FILES.items():
        actual = path.read_text(encoding="utf-8") if path.is_file() else ""
        expected = normalized(expected)
        if actual == expected:
            continue
        stale.append(path)
        print(f"STALE: {path.relative_to(ROOT)}")
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"current/{path.relative_to(ROOT)}",
            tofile=f"expected/{path.relative_to(ROOT)}",
            lineterm="",
        )
        for line in diff:
            print(line)
    for path, expected_target in ALIASES.items():
        actual = alias_target(path)
        if actual == expected_target:
            continue
        stale.append(path)
        print(
            f"STALE: {path.relative_to(ROOT)} "
            f"(expected compatibility target {expected_target}, found {actual or 'missing'})"
        )
    if stale:
        print(f"Harness routing check failed for {len(stale)} file(s).")
        return 1
    print(
        f"Harness routing check passed for {len(FILES)} router(s) "
        f"and {len(ALIASES)} compatibility alias(es)."
    )
    return 0


def refresh() -> int:
    for path, content in FILES.items():
        path.write_text(normalized(content), encoding="utf-8")
        print(f"Refreshed: {path.relative_to(ROOT)}")
    for path, target in ALIASES.items():
        if alias_target(path) == target:
            print(f"Kept alias: {path.relative_to(ROOT)} -> {target}")
            continue
        if path.exists() or path.is_symlink():
            path.unlink()
        try:
            path.symlink_to(target)
            print(f"Refreshed alias: {path.relative_to(ROOT)} -> {target}")
        except OSError:
            path.write_text(target + "\n", encoding="utf-8")
            print(f"Refreshed portable alias: {path.relative_to(ROOT)} -> {target}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated routers without writing",
    )
    args = parser.parse_args()
    return check() if args.check else refresh()


if __name__ == "__main__":
    raise SystemExit(main())
